version: '2'

services:
  gasoil-db:
    image: mysql:8.0
    container_name: gasoil-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3314:3306
    extends:
      file: ./mysql/password.yml
      service: password
    volumes:
      - ./mysql/data:/var/lib/mysql
